version: "3.9"

services:
  # -------------------- FRONTEND --------------------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - synapse-network

  # -------------------- BACKEND --------------------
  backend:
    build:
      context: ../Synapse-Backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../Synapse-Backend:/code
    env_file:
      - ../Synapse-Infra/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
    environment:
      - TRANSFORMERS_CACHE=/hf_cache
      - HF_HOME=/hf_cache
    networks:
      - synapse-network

  # -------------------- REDIS --------------------
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - synapse-network

  # -------------------- POSTGRES --------------------
  postgres:
    image: pgvector/pgvector:pg13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - synapse-network

  # -------------------- QDRANT VECTOR DATABASE --------------------
  qdrant:
    image: qdrant/qdrant:latest
    container_name: synapse-qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - synapse-network

# -------------------- NAMED VOLUMES --------------------
volumes:
  pgdata_dev: {}
  qdrant_data: {}

# -------------------- NETWORKS --------------------
networks:
  synapse-network:
    driver: bridge